"""target application is_active

Revision ID: 57b21385ef0b
Revises: 26574bbf0754
Create Date: 2026-09-12 00:49:25.042765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b21385ef0b'
down_revision: Union[str, None] = '26574bbf0754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_applications', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_applications', 'is_active')
    # ### end Alembic commands ###
