"""referential: partner directory, target applications, routing rules, oauth apps, users

Revision ID: 7f5f17e52a8d
Revises: bbdeda150f92
Create Date: 2026-09-11 16:39:45.263125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5f17e52a8d'
down_revision: Union[str, None] = 'bbdeda150f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_directories_siren'), 'partner_directories', ['siren'], unique=False)
    op.create_index(op.f('ix_partner_directories_siret'), 'partner_directories', ['siret'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oidc_subject')
    )
    op.create_table('company_users',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'user_id')
    )
    op.create_table('oauth_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('app_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('redirect_urls', sa.String(length=2000), nullable=True),
    sa.Column('preferred_conversion_format', sa.String(length=50), nullable=True),
    sa.Column('afnor_api_version', sa.String(length=10), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_applications_client_id'), 'oauth_applications', ['client_id'], unique=True)
    op.create_table('target_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('routing_method', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_directory_id', sa.Integer(), nullable=False),
    sa.Column('target_application_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['partner_directory_id'], ['partner_directories.id'], ),
    sa.ForeignKeyConstraint(['target_application_id'], ['target_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_rules')
    op.drop_table('target_applications')
    op.drop_index(op.f('ix_oauth_applications_client_id'), table_name='oauth_applications')
    op.drop_table('oauth_applications')
    op.drop_table('company_users')
    op.drop_table('users')
    op.drop_index(op.f('ix_partner_directories_siret'), table_name='partner_directories')
    op.drop_index(op.f('ix_partner_directories_siren'), table_name='partner_directories')
    op.drop_table('partner_directories')
    # ### end Alembic commands ###
