"""lot 7: ip allowlist on router settings

Revision ID: aadbc5569518
Revises: 81551b3b4fa0
Create Date: 2026-09-11 17:32:56.580473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadbc5569518'
down_revision: Union[str, None] = '81551b3b4fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('router_settings', sa.Column('ihm_ip_allowlist', sa.Text(), nullable=True))
    op.add_column('router_settings', sa.Column('afnor_api_ip_allowlist', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('router_settings', 'afnor_api_ip_allowlist')
    op.drop_column('router_settings', 'ihm_ip_allowlist')
    # ### end Alembic commands ###
