"""invoicing: invoice and invoice_routing tables

Revision ID: cd1ac096c1fa
Revises: 7f5f17e52a8d
Create Date: 2026-09-11 16:44:30.921722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1ac096c1fa'
down_revision: Union[str, None] = '7f5f17e52a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('partner_directory_id', sa.Integer(), nullable=True),
    sa.Column('emitter_siren', sa.String(length=9), nullable=False),
    sa.Column('emitter_siret', sa.String(length=14), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=30), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('superpdp_flow_id', sa.String(length=100), nullable=False),
    sa.Column('superpdp_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('superpdp_updated_at', sa.DateTime(), nullable=True),
    sa.Column('amount_total', sa.Float(), nullable=True),
    sa.Column('amount_excl_tax', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('syntax', sa.String(length=30), nullable=True),
    sa.Column('processing_rule', sa.String(length=30), nullable=True),
    sa.Column('afnor_metadata', sa.JSON(), nullable=False),
    sa.Column('afnor_api_version', sa.String(length=10), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_directory_id'], ['partner_directories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'superpdp_flow_id', name='uq_invoice_company_flow')
    )
    op.create_index(op.f('ix_invoices_emitter_siren'), 'invoices', ['emitter_siren'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_superpdp_flow_id'), 'invoices', ['superpdp_flow_id'], unique=False)
    op.create_table('invoice_routings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('target_application_id', sa.Integer(), nullable=False),
    sa.Column('transfer_status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['target_application_id'], ['target_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'target_application_id', name='uq_routing_invoice_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_routings')
    op.drop_index(op.f('ix_invoices_superpdp_flow_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_emitter_siren'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
