"""afnor server: flow traces, oauth client secret hash, target app oauth link

Revision ID: d9f081c6f654
Revises: e6eedab4d364
Create Date: 2026-09-11 16:58:32.068179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f081c6f654'
down_revision: Union[str, None] = 'e6eedab4d364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('afnor_api_version', sa.String(length=10), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_traces_correlation_id'), 'flow_traces', ['correlation_id'], unique=False)

    # SQLite ne supporte pas ALTER TABLE ADD CONSTRAINT : mode batch (copy-and-move).
    with op.batch_alter_table('oauth_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret_hash', sa.String(length=255), nullable=False, server_default=''))
        batch_op.drop_column('client_secret')
    with op.batch_alter_table('oauth_applications', schema=None) as batch_op:
        batch_op.alter_column('client_secret_hash', server_default=None)

    with op.batch_alter_table('target_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_target_applications_oauth_application_id',
            'oauth_applications',
            ['oauth_application_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_target_applications_oauth_application_id', type_='foreignkey')
        batch_op.drop_column('oauth_application_id')

    with op.batch_alter_table('oauth_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.VARCHAR(length=255), nullable=False, server_default=''))
        batch_op.drop_column('client_secret_hash')
    with op.batch_alter_table('oauth_applications', schema=None) as batch_op:
        batch_op.alter_column('client_secret', server_default=None)

    op.drop_index(op.f('ix_flow_traces_correlation_id'), table_name='flow_traces')
    op.drop_table('flow_traces')
    # ### end Alembic commands ###
