"""initial schema

Revision ID: e6c2d757f43b
Revises: 
Create Date: 2026-09-11 18:23:26.862018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c2d757f43b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_manager_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_siren'), 'companies', ['siren'], unique=True)
    op.create_table('flow_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('afnor_api_version', sa.String(length=10), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_traces_correlation_id'), 'flow_traces', ['correlation_id'], unique=False)
    op.create_table('partner_directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_directories_siren'), 'partner_directories', ['siren'], unique=False)
    op.create_index(op.f('ix_partner_directories_siret'), 'partner_directories', ['siret'], unique=False)
    op.create_table('router_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical_log_retention_days', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_from_address', sa.String(length=255), nullable=True),
    sa.Column('ihm_ip_allowlist', sa.Text(), nullable=True),
    sa.Column('afnor_api_ip_allowlist', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oidc_subject')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('company_users',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'user_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('partner_directory_id', sa.Integer(), nullable=True),
    sa.Column('emitter_siren', sa.String(length=9), nullable=False),
    sa.Column('emitter_siret', sa.String(length=14), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=30), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('superpdp_flow_id', sa.String(length=100), nullable=False),
    sa.Column('superpdp_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('superpdp_updated_at', sa.DateTime(), nullable=True),
    sa.Column('amount_total', sa.Float(), nullable=True),
    sa.Column('amount_excl_tax', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('syntax', sa.String(length=30), nullable=True),
    sa.Column('processing_rule', sa.String(length=30), nullable=True),
    sa.Column('afnor_metadata', sa.JSON(), nullable=False),
    sa.Column('afnor_api_version', sa.String(length=10), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_directory_id'], ['partner_directories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'superpdp_flow_id', name='uq_invoice_company_flow')
    )
    op.create_index(op.f('ix_invoices_emitter_siren'), 'invoices', ['emitter_siren'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_superpdp_flow_id'), 'invoices', ['superpdp_flow_id'], unique=False)
    op.create_table('oauth_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('token_cache', sa.Text(), nullable=True),
    sa.Column('app_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('redirect_urls', sa.String(length=2000), nullable=True),
    sa.Column('preferred_conversion_format', sa.String(length=50), nullable=True),
    sa.Column('afnor_api_version', sa.String(length=10), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_applications_client_id'), 'oauth_applications', ['client_id'], unique=True)
    op.create_table('technical_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_logs_created_at'), 'technical_logs', ['created_at'], unique=False)
    op.create_table('afnor_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('flow_type', sa.String(length=30), nullable=False),
    sa.Column('syntax', sa.String(length=20), nullable=False),
    sa.Column('processing_rule', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('file_bin', sa.LargeBinary(), nullable=True),
    sa.Column('data_dict', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('routing_method', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('oauth_application_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['oauth_application_id'], ['oauth_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_routings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('target_application_id', sa.Integer(), nullable=False),
    sa.Column('transfer_status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['target_application_id'], ['target_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'target_application_id', name='uq_routing_invoice_target')
    )
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('afnor_flow_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['afnor_flow_id'], ['afnor_flows.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_directory_id', sa.Integer(), nullable=False),
    sa.Column('target_application_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['partner_directory_id'], ['partner_directories.id'], ),
    sa.ForeignKeyConstraint(['target_application_id'], ['target_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_event_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lifecycle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_event_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lifecycle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_event_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['lifecycle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifecycle_event_payments')
    op.drop_table('lifecycle_event_details')
    op.drop_table('lifecycle_event_attachments')
    op.drop_table('routing_rules')
    op.drop_table('lifecycle_events')
    op.drop_table('invoice_routings')
    op.drop_table('target_applications')
    op.drop_table('afnor_flows')
    op.drop_index(op.f('ix_technical_logs_created_at'), table_name='technical_logs')
    op.drop_table('technical_logs')
    op.drop_index(op.f('ix_oauth_applications_client_id'), table_name='oauth_applications')
    op.drop_table('oauth_applications')
    op.drop_index(op.f('ix_invoices_superpdp_flow_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_emitter_siren'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('company_users')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('router_settings')
    op.drop_index(op.f('ix_partner_directories_siret'), table_name='partner_directories')
    op.drop_index(op.f('ix_partner_directories_siren'), table_name='partner_directories')
    op.drop_table('partner_directories')
    op.drop_index(op.f('ix_flow_traces_correlation_id'), table_name='flow_traces')
    op.drop_table('flow_traces')
    op.drop_index(op.f('ix_companies_siren'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('billing_manager_contacts')
    # ### end Alembic commands ###
