"""lifecycle: events, details, payments, attachments, afnor flows

Revision ID: e6eedab4d364
Revises: cd1ac096c1fa
Create Date: 2026-09-11 16:51:41.338373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6eedab4d364'
down_revision: Union[str, None] = 'cd1ac096c1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afnor_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('flow_type', sa.String(length=30), nullable=False),
    sa.Column('syntax', sa.String(length=20), nullable=False),
    sa.Column('processing_rule', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('file_bin', sa.LargeBinary(), nullable=True),
    sa.Column('data_dict', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('afnor_flow_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['afnor_flow_id'], ['afnor_flows.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_event_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lifecycle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_event_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['lifecycle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_event_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['lifecycle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifecycle_event_payments')
    op.drop_table('lifecycle_event_details')
    op.drop_table('lifecycle_event_attachments')
    op.drop_table('lifecycle_events')
    op.drop_table('afnor_flows')
    # ### end Alembic commands ###
